//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSourceControls.Task01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Population { get; set; }
        public int Country { get; set; }
    
        public virtual Country Country1 { get; set; }
    }
}
