//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/1z31es0.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/belleandbeast.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/character04%20-%20jaq.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/characters_bolt.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/cheshire_cat_khrec.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/jiminy1.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/mickey.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/rafiki2.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/sully.png")]


